applications:
- name: bookshelf-api
  memory: 512MB
  timeout: 180
  buildpack: https://github.com/cloudfoundry/python-buildpack.git
  command: flask db upgrade && flask run --port 8080 --host 0.0.0.0
  services:
  - bookshelf_psql
  routes:
  - route: bookshelf-dev.apps.pcfone.io/api
